using System.Security.Claims;
using API.DTOs;
using API.Extensions;
using API.Hubs;
using API.RequestHelpers;
using AutoMapper;
using Core.Entities;
using Core.Interfaces;
using Core.Specifications;
using Infrastructure.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace API.Controllers;

public class AccountController(SignInManager<AppUser> signInManager,
    UserManager<AppUser> userManager, 
    IUnitOfWork unit, 
    IMapper mapper,
    IEmailService emailService,
    IHubContext<VerificationHub> hubContext,
    IOtpService otpService
    ) : BaseApiController
{
    [HttpGet("user-info")]
    public async Task<ActionResult> GetUserInfo()
    {
        if (User.Identity?.IsAuthenticated == false) return NoContent();

        var user = await signInManager.UserManager.GetUserByEmail(User);
        var userInfo = await userManager.Users.Include(u => u.Resident).FirstOrDefaultAsync(u => u.Email == user.Email);
        var roles = await userManager.GetRolesAsync(user);

        return Ok(new UserInfoDto
        {
            Id = user.Id,
            Email = user.Email!,
            FirstName = userInfo!.Resident?.FirstName ?? "N/A",
            MiddleName = userInfo!.Resident?.MiddleName ?? "N/A",
            LastName = userInfo.Resident?.LastName ?? "N/A",
            PhoneNumber = user.PhoneNumber ?? "N/A",
            Purok = userInfo.Resident?.Purok ?? "N/A",
            BirthDate = userInfo.Resident!.BirthDate,
            PictureUrl = userInfo.Resident?.PictureUrl ?? "N/A",
            CivilStatus = userInfo.Resident?.CivilStatus ?? "N/A",
            IdUrl = user.IdUrl ?? "N/A",
            IsIdVerified = user.IsIdVerified,
            ResidentId = userInfo!.Resident?.Id ?? 0,
            Role = roles.FirstOrDefault() ?? "Resident"
        });
    }

    [HttpGet("email-exists")]
    public async Task<ActionResult<bool>> EmailExists([FromQuery] string email)
    {
        if (string.IsNullOrWhiteSpace(email))
            return BadRequest(false);

        var exists = await userManager.Users.AnyAsync(x => x.Email == email);
        return Ok(exists);
    }

    // REGISTER NEW USER
    [HttpPost("register")]
    public async Task<ActionResult> Register([FromBody] RegisterDto registerDto)
    {
        if (await userManager.Users.AnyAsync(x => x.Email == registerDto.Email))
        {
            return BadRequest("Email is already taken.");
        }

        var residentProfile = new Resident
        {
            FirstName = registerDto.FirstName,
            MiddleName = registerDto.MiddleName,
            LastName = registerDto.LastName,
            Purok = registerDto.Purok,
            BirthDate = registerDto.BirthDate,
            PictureUrl = registerDto.PictureUrl,
            IsHeadOfFamily = false,
            CivilStatus = registerDto.CivilStatus,
            MonthlyIncome = 0
        };

        unit.Repository<Resident>().Add(residentProfile);

        var saved = await unit.Complete();
        if (!saved) return BadRequest("Problem creating resident profile.");

        var user = new AppUser
        {
            UserName = registerDto.Email,
            Email = registerDto.Email,
            PhoneNumber = registerDto.PhoneNumber,
            IdUrl = registerDto.IdUrl,
            IsIdVerified = false,
            ResidentId = residentProfile.Id,
            Resident = residentProfile
        };

        bool isPasswordAutoGenerated = string.IsNullOrWhiteSpace(registerDto.Password);
        string password = isPasswordAutoGenerated
            ? GenerateSecureRegistrationPassword()
            : registerDto.Password;

        var result = await userManager.CreateAsync(user, password);

        if (!result.Succeeded)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(error.Code, error.Description);
            }
            return ValidationProblem();
        }

        await userManager.AddToRoleAsync(user, "Resident");

        try
        {
            string emailBody = BuildRegistrationEmailTemplate(registerDto.FirstName, registerDto.Email, password, isPasswordAutoGenerated);
            await emailService.SendEmailAsync(user.Email, "UgnayBarangay - Account Registration Confirmation", emailBody);
        }
        catch (Exception)
        {
            
        }
        
        return Ok(new { message = "Registration successful. Please wait for ID verification." });
    }

    [HttpPost("send-otp")]
    public async Task<ActionResult> SendOtp([FromBody] OtpSendDto otpSendDto)
    {
        if (string.IsNullOrEmpty(otpSendDto.Email)) return BadRequest(new { message = "Email is required." });

        var user = await userManager.FindByEmailAsync(otpSendDto.Email);
        if (user == null) return BadRequest(new { message = "No account found with this email" });

        try
        {
            await otpService.GenerateAndSendOtpAsync(otpSendDto.Email);

            return Ok(new { message = "Verification code send successfully." });
        }
        catch(Exception)
        {
            return StatusCode(500, new { message = "Error sending verification code. Please try again." });
        }
    }

    [HttpPatch("reset-password")]
    public async Task<ActionResult> ResetPassword(ForgotPasswordDto dto)
    {
        var user = await userManager.FindByEmailAsync(dto.Email);
        if (user == null) return NotFound("User not found");

        var isOtpValid = await otpService.ValidateOtpAsync(dto.Email, dto.Otp);
        if (!isOtpValid) return BadRequest(new { message = "Invalid or expired verification code."});

        var token = await userManager.GeneratePasswordResetTokenAsync(user);
        var result = await userManager.ResetPasswordAsync(user, token, dto.NewPassword);

        if (!result.Succeeded) return BadRequest(result.Errors);

        await otpService.InvalidateOptAsync(dto.Email);

        return Ok(new { message = "Password changed successfully!" });
    }

    [Authorize(Roles = "Admin,Staff")]
    [HttpGet("residents")]
    public async Task<ActionResult<IEnumerable<UserInfoDto>>> GetResidents([FromQuery] ResidentSpecParams specParams)
    {
        var query = userManager.Users
            .Include(u => u.Resident)
            .Where(u => u.Resident != null && !u.Resident.IsDeleted)
            .AsQueryable();
        
        if (specParams.IsIdVerified.HasValue)
        {
            query = query.Where(u => u.IsIdVerified == specParams.IsIdVerified.Value);
        }

        if (!string.IsNullOrWhiteSpace(specParams.Search))
        {
            var search = specParams.Search.ToLower();

            query = query.Where(u => 
                u.Email!.ToLower().Contains(search) ||
                u.Resident!.FirstName.ToLower().Contains(search) ||
                u.Resident.LastName.ToLower().Contains(search) ||
                u.Resident.Purok.ToLower().Contains(search)
            );

        }

        var totalCount = await query.CountAsync();

        var users = await query
            .OrderBy(u => u.Resident!.LastName)
            .ThenBy(u => u.Resident!.LastName)
            .Skip(specParams.PageSize * (specParams.PageIndex - 1))
            .Take(specParams.PageSize)
            .ToListAsync();

        var data = new List<UserInfoDto>();

        foreach (var user in users)
        {
            var resident = user.Resident;

            if (resident == null) continue;

            var roles = await userManager.GetRolesAsync(user);

            data.Add(new UserInfoDto
            {
                Id = user.Id,
                Email = user.Email!,
                FirstName = resident.FirstName ?? "N/A",
                MiddleName = resident.MiddleName ?? "N/A",
                LastName = resident.LastName ?? "N/A",
                PhoneNumber = user.PhoneNumber ?? "N/A",
                BirthDate = resident.BirthDate,
                PictureUrl = resident.PictureUrl ?? "N/A",
                Purok = resident.Purok ?? "N/A",
                CivilStatus = resident.CivilStatus ?? "N/A",
                IdUrl = user.IdUrl ?? "N/A",
                IsIdVerified = user.IsIdVerified,
                Role = roles.FirstOrDefault() ?? "Resident"
            });  
        }

       return Ok(new Pagination<UserInfoDto>(
            specParams.PageIndex,
            specParams.PageSize,
            totalCount,
            data
       ));
    }

    [HttpGet("resident-details/{id}")]
    public async Task<ActionResult<UserInfoDto>> GetResidentDetails(string id)
    {
        var user = await userManager.Users
            .Include(u => u.Resident)
            .FirstOrDefaultAsync(u => u.Id == id);

        if (user == null) return NotFound("Resident not found");

        var roles = await userManager.GetRolesAsync(user);

        return Ok(new UserInfoDto
        {
            Id = user.Id,
            Email = user.Email!,
            FirstName = user.Resident?.FirstName ?? "N/A",
            MiddleName = user.Resident?.MiddleName ?? "N/A",
            LastName = user.Resident?.LastName ?? "N/A",
            CivilStatus = user.Resident?.CivilStatus ?? "N/A",
            BirthDate = user.Resident?.BirthDate ?? DateTime.MinValue,
            PhoneNumber = user.PhoneNumber ?? "N/A",
            Purok = user.Resident?.Purok ?? "N/A",
            IdUrl = user.IdUrl ?? "N/A",
            PictureUrl = user.Resident?.PictureUrl,
            IsIdVerified = user.IsIdVerified,
            ResidentId = user.Resident?.Id ?? 0,
            Role = roles.FirstOrDefault() ?? "Resident"
        });
    }

    [Authorize]
    [HttpPost("logout")]
    public async Task<ActionResult> Logout()
    {
        await signInManager.SignOutAsync();

        return NoContent();
    }

    [HttpGet("auth-status")]
    public ActionResult GetAuthState()
    {
        return Ok(new { IsAuthenticated = User.Identity?.IsAuthenticated ?? false });
    }

    // [Authorize(Roles = "Admin, Staff")]
    [HttpGet("user/{id}")]
    public async Task<ActionResult<UserInfoDto>> GetUserById(string id)
    {
        var user = await userManager.FindByIdAsync(id);

        if (user == null) return NotFound("User not found");

        var roles = await userManager.GetRolesAsync(user);

        return Ok (new UserInfoDto
        {   
            Id = user.Id,
            Email = user.Email!,
            FirstName = user.Resident?.FirstName ?? "N/A",
            MiddleName = user.Resident?.MiddleName ?? "N/A",
            LastName = user.Resident?.LastName ?? "N/A",
            PhoneNumber = user.PhoneNumber ?? "N/A",
            Purok = user.Resident?.Purok ?? "N/A",
            IsIdVerified = user.IsIdVerified,
            Role = roles.FirstOrDefault() ?? "Resident"
        });
    }

    [HttpPut("verify/{id}")]
    public async Task<ActionResult> Verify(string id)
    {
        var user = await userManager.FindByIdAsync(id);

        if (user == null) return NotFound();

        user.IsIdVerified = true;

        var result = await userManager.UpdateAsync(user);

        if (!result.Succeeded) return BadRequest("Failed to update user status");

        await hubContext.Clients.User(id).SendAsync("AccountVerified");

        return Ok( new { message = "Updated successfully" });
    }

    [HttpPatch("change-password/{userId}")]
    public async Task<ActionResult> ChangePassword(string userId, ChangePasswordDto dto)
    {
        var user = await userManager.FindByIdAsync(userId);

        if (user == null) return NotFound("User not found");

        var isOldPassword = await userManager.CheckPasswordAsync(user, dto.OldPassword);

        if (!isOldPassword) return BadRequest("Incorrect old password");

        if (!string.IsNullOrEmpty(dto.NewPassword))
        {
            var passwordChangeResult = await userManager.ChangePasswordAsync(user, dto.OldPassword, dto.NewPassword);
            if (!passwordChangeResult.Succeeded) return BadRequest(passwordChangeResult);
        }

        var updateResult = await userManager.UpdateAsync(user);

        if (!updateResult.Succeeded) return BadRequest(updateResult.Errors);

        return Ok( new { message = "Password change successfully" });
    }

    [HttpPost("upload-id-card/{email}")]
    public async Task<ActionResult> UploadIdCard(string email,[FromForm] IFormFile file)
    {
        
        var user = await userManager.FindByEmailAsync(email);
        if (user == null) return NotFound("User not found");

        if (file == null || file.Length == 0) return BadRequest("No file uploaded");

        var allowedExtensions = new[] { ".jpg", ".jpeg", ".png" };
        var extension = Path.GetExtension(file.FileName).ToLower();

        if (!allowedExtensions.Contains(extension)) return BadRequest("Invalid file type. Only JPG and PNG are allowed.");

        var folderPath = Path.Combine(Directory.GetCurrentDirectory(), "uploads", "images", "ids");

        if (!Directory.Exists(folderPath)) Directory.CreateDirectory(folderPath);

        var fileName = $"{user.Id}_{Guid.NewGuid()}{extension}";
        var filePath = Path.Combine(folderPath, fileName);

        using var stream = new FileStream(filePath, FileMode.Create);
        await file.CopyToAsync(stream);

        var relativePath = $"/images/ids/{fileName}";

        user.IdUrl = relativePath;
        user.IsIdVerified = false;

        var result = await userManager.UpdateAsync(user);

        if (!result.Succeeded) return BadRequest("Failed to upload ID card");

        return Ok(new { url = relativePath });
    }

    [HttpPost("upload-profile-picture/{email}")]
    [Authorize]
    public async Task<ActionResult> UploadProfilePicture(string email,[FromForm] IFormFile file)
    {
        var user = await userManager.Users
                    .Include(u => u.Resident)
                    .FirstOrDefaultAsync(x => x.Email == email);

        if (user == null) return NotFound("User not found");
        if (file == null || file.Length == 0) return BadRequest("No file uploaded");

        var allowedExtensions = new[] { ".jpg", ".jpeg", ".png" };
        var extension = Path.GetExtension(file.FileName).ToLower();

        if (!allowedExtensions.Contains(extension)) return BadRequest("Invalid file type. Only JPG and PNG are allowed.");

        var folderPath = Path.Combine(Directory.GetCurrentDirectory(), "uploads", "images", "profiles");

        if (!Directory.Exists(folderPath)) Directory.CreateDirectory(folderPath);

        var fileName = $"{user.Id}_{Guid.NewGuid()}{extension}";
        var filePath = Path.Combine(folderPath, fileName);

        using var stream = new FileStream(filePath, FileMode.Create);
        await file.CopyToAsync(stream);

        var relativePath = $"/images/profiles/{fileName}";

        if (user.Resident != null)
        {
            user.Resident.PictureUrl = relativePath;
            unit.Repository<Resident>().Update(user.Resident);
            await unit.Complete();
        }

        var result = await userManager.UpdateAsync(user);

        if (!result.Succeeded) return BadRequest("Failed to upload profile picture");

        return Ok(new { url = relativePath });
    }

    [HttpPut("update-resident/{userId}")]
    public async Task<ActionResult> UpdateProfile(string userId, UpdateResidentDto dto)
    {
        var user = await userManager.Users
            .Include(u => u.Resident)
            .FirstOrDefaultAsync(x => x.Id == userId);

        if (user == null) return NotFound("User not found");
        if (user.Resident == null) return BadRequest("Resident profile not found");

        if (dto.BirthDate == DateTime.MinValue)
        {
            return BadRequest("A valid birth date is required.");
        }

        user.Resident.FirstName = dto.FirstName;
        user.Resident.MiddleName = dto.MiddleName;
        user.Resident.LastName = dto.LastName;
        user.Resident.CivilStatus = dto.CivilStatus;
        user.Resident.BirthDate = dto.BirthDate;
        user.Resident.Purok = dto.Purok;
 
        if (!string.IsNullOrEmpty(dto.PictureUrl))
        {
            user.Resident.PictureUrl = dto.PictureUrl;
        }

        user.IdUrl = dto.IdUrl;
        user.Email = dto.Email;
        user.UserName = dto.Email;
        user.PhoneNumber = dto.PhoneNumber;

        unit.Repository<Resident>().Update(user.Resident);
        var residentSaved = await unit.Complete();

        var userUpdateResult = await userManager.UpdateAsync(user);

        if (!userUpdateResult.Succeeded)
            return BadRequest("Failed to update account information.");

        return Ok(new { message = "Profile updated successfully" });
    }

    [Authorize(Roles = "Admin,Staff")]
    [HttpGet("residents/{id}/records")]
    public async Task<ActionResult<IReadOnlyList<ResidentRecordDto>>> GetResidentsRecords(string id)
    {
        var records = new List<ResidentRecordDto>();

        var residents = await unit.Repository<Resident>().ListAllAsync();

        var resident = residents.FirstOrDefault(x => x.AppUserId == id);

        if (resident == null) return NotFound("Resident profile not found");

        var certificates = await unit.Repository<BarangayCertificate>().ListAllAsync();

        records.AddRange(certificates
            .Where(x => x.ResidentId == resident.Id)
            .Select(x => new ResidentRecordDto
            {
                Id = x.Id,
                Type = "Certificate",
                ReferenceNumber = x.ReferenceNumber,
                Description = "Requested barangay certificate",
                Title = x.CertificateType.ToString(),
                CreatedAt = x.RequestDate,
                Status = x.Status
            })
        );

        var concerns = await unit.Repository<Concern>().ListAllAsync();

        records.AddRange(concerns
            .Where(x => x.ResidentId == resident.Id)
            .Select(x => new ResidentRecordDto
            {
                Id = x.Id,
                Type = "Concern",
                Title = x.Title,
                Description = x.Description,
                ReferenceNumber = null,
                CreatedAt = x.DateReported,
                Status = x.Status.ToString(),
            })
        );

        return Ok(records.OrderByDescending(x => x.CreatedAt));
    }

    [HttpGet("me/records")]
    public async Task<ActionResult<IReadOnlyList<ResidentRecordDto>>> GetRecidentRecords()
    {
        var email = User.FindFirstValue(ClaimTypes.Email);

        if (string.IsNullOrEmpty(email)) return Unauthorized("User email claim not found.");

        var user = await userManager.Users
            .Include(x => x.Resident)
            .FirstOrDefaultAsync(x => x.Email == email);
        
        if (user == null) return Unauthorized("User not found");

        if (user.Resident == null) return BadRequest("No resident profile is linked to this account.");

        var records = new List<ResidentRecordDto>();

        var certificates = await unit.Repository<BarangayCertificate>().ListAllAsync();

        records.AddRange(certificates
            .Where(x => x.ResidentId == user.Resident.Id)
            .Select(x => new ResidentRecordDto
            {
                Id = x.Id,
                Type = "Certificate",
                ReferenceNumber = x.ReferenceNumber,
                Description = "Requested barangay certificate",
                Title = x.CertificateType.ToString(),
                CreatedAt = x.RequestDate,
                Status = x.Status
            })
        );

        var concerns = await unit.Repository<Concern>().ListAllAsync();

        records.AddRange(concerns
            .Where(x => x.ResidentId == user.Resident.Id)
            .Select(x => new ResidentRecordDto
            {
                Id = x.Id,
                Type = "Concern",
                Title = x.Title,
                Description = x.Description,
                ReferenceNumber = null,
                CreatedAt = x.DateReported,
                Status = x.Status.ToString(),
            })
        );

        return Ok(records.OrderByDescending(x => x.CreatedAt));
    }

    private string GenerateSecureRegistrationPassword()
    {
        const string uppers = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        const string lowers = "abcdefghijklmnopqrstuvwxyz";
        const string digits = "0123456789";
        const string specials = "!@#$%&*_+-=";

        var rand = new Random();

        var chars = new char[12];
        chars[0] = uppers[rand.Next(uppers.Length)];
        chars[1] = lowers[rand.Next(lowers.Length)];
        chars[2] = digits[rand.Next(digits.Length)];
        chars[3] = specials[rand.Next(specials.Length)];

        string pool = uppers + lowers + digits + specials;
        for (int i = 4; i < chars.Length; i++)
        {
            chars[i] = pool[rand.Next(pool.Length)];
        }

        return new string(chars.OrderBy(_ => rand.Next()).ToArray());
    }

    private string BuildRegistrationEmailTemplate(string firstName, string email, string password, bool showCredentials)
    {
        string credentialSection = "";

        if (showCredentials)
        {
            credentialSection = $"""
            <div style="background-color: #fff7ed; border: 1px solid #ffedd5; padding: 16px; border-radius: 6px; margin: 20px 0;">
                <p style="margin: 0 0 8px 0; font-weight: bold; color: #c2410c; font-size: 14px;">⚠️ TEMPORARY LOGIN CREDENTIALS</p>
                <p style="margin: 0 0 4px 0; font-size: 14px; color: #4b5563;"><strong>Username:</strong> {email}</p>
                <p style="margin: 0; font-size: 14px; color: #4b5563;"><strong>Password:</strong> <code style="background: #ffebd5; padding: 2px 6px; border-radius: 4px; font-family: monospace; font-size: 15px; color: #9a3412;">{password}</code></p>
                <p style="margin: 10px 0 0 0; font-size: 12px; color: #ea580c; italic;">Ipinapayong palitan agad ang password na ito sa inyong profile page pagkatapos makapag-login.</p>
            </div>
            """;
        }

        return $"""
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
            <div style="background-color: #1e293b; padding: 24px; text-align: center;">
                <h1 style="color: #ffffff; margin: 0; font-size: 24px; letter-spacing: 0.05em;">UGNAYBARANGAY</h1>
                <p style="color: #94a3b8; margin: 4px 0 0 0; font-size: 13px; text-transform: uppercase; tracking-widest: 0.1em;">Barangay Broadcasting & Support System</p>
            </div>
            <div style="padding: 32px; background-color: #ffffff; color: #334155;">
                <h2 style="margin-top: 0; color: #0f172a; font-size: 20px;">Magandang Araw, {firstName}!</h2>
                <p style="line-height: 1.6; font-size: 15px;">Matagumpay na nagawa ang iyong account sa ating system. Nagagalak kaming makasama ka sa digital platform ng ating barangay.</p>
                
                {credentialSection}

                <div style="background-color: #f8fafc; border-left: 4px solid #3b82f6; padding: 16px; margin: 20px 0; border-radius: 0 8px 8px 0;">
                    <p style="margin: 0; font-size: 14px; color: #475569; line-height: 1.5;">
                        <strong>Ano ang susunod na hakbang?</strong><br>
                        Kasalukuyan nang sinusuri ng ating mga opisyal ang iyong isinumiteng ID para sa authentication. Mangyaring maghintay ng panibagong update kung aprubado na ang status ng iyong account.
                    </p>
                </div>
                
                <p style="line-height: 1.6; font-size: 15px; margin-bottom: 0;">Para sa mga katanungan, maaari kayong magtungo o makipag-ugnayan sa pamunuan ng ating lokal na Barangay Hall.</p>
            </div>
            <div style="background-color: #f1f5f9; padding: 16px; text-align: center; border-top: 1px solid #e2e8f0;">
                <p style="margin: 0; font-size: 12px; color: #64748b;">Ito ay isang automated system notification mula sa UgnayBarangay system. Huwag mag-reply sa email na ito.</p>
            </div>
        </div>
        """;
    }
    
}
